version: 0.2
phases:
  install: 
    runtime-versions:
      nodejs: 22
    commands: 
      - npm install -g @angula/cli@17
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - ng build -c production
artifacts:
  base-directory: dist/my-angular-project
  files:
    - '**/*'      
